### ISSUE TITLE
请问关于minidao 1.5.1版本的，连接池泄露问题是怎么解决的呢？

### ISSUE THREAD

**Issue by andotorg** [zhangdaiscott/MiniDao#10]
### 连接池泄露问题

> 这里输入引用文本由于项目中使用了minidao 1.5.1，hibernate的增删改查不需要书写sql语句的地方造成程序运行的时候出现了连接池泄露，数据库连接数一直在300以上。

#### 书写测试代码

![遍历插入测试代码](https://gitee.com/uploads/images/2018/0425/102837_edfafe04_774608.png "测试代码.png")

#### 执行前数据库连接数

![执行前](https://gitee.com/uploads/images/2018/0425/102914_17ac1eb0_774608.png "执行前.png")

#### 执行后数据库连接数

![执行后连接数](https://gitee.com/uploads/images/2018/0425/102933_ab2b0d8a_774608.png "执行后.png")

#### minidao源代码

![minidao源代码](https://gitee.com/uploads/images/2018/0425/102955_6b5142df_774608.jpeg "源代码.jpg")

> 这些测试说明了，使用xxxByHiber的进行数据库操作都会差生一个连接，并且不会关闭。

```
        //*********************test source(数据库中字段设置很小所以抛异常)******************
        for (int i = 0; i < 50; i++) {
			BI_DIM bi_DIM = new BI_DIM();
			if(i > 20)
				    
       bi_DIM.setBiz_Table_Name("123====================================================================="+i);
			else
				bi_DIM.setBiz_Table_Name("123===="+i);
			bi_DIM.setDim_Name("测试");
			bi_DIM.setDrill_Info("");
			try {
				dimDao.saveByHiber(bi_DIM);
			} catch (Exception e) {
				System.err.println("抛异常了"+i+"; info:"+e.getMessage());
			}
		}
		return "";

        //**********************minidao source********************************************
        /**
	 * 根据传入的实体持久化对象
	 */
	public <T> void save(T entity) {
		try {
			getSession().save(entity);
			getSession().flush();
			if (logger.isDebugEnabled()) {
				logger.debug("保存实体成功," + entity.getClass().getName());
			}
		} catch (RuntimeException e) {
			logger.error("保存实体异常", e);
			getSession().close();
			throw e;
		}

	}
```

> 我觉得你们肯定不可能没有发现！

> 希望你们对于此事尽快给一个答复！！！

[文章图片请看这里](https://gitee.com/jeecg/minidao/issues/IJBTN)
[文章图片请看这里](https://gitee.com/jeecg/minidao/issues/IJBTN)

**Comment by zhangdaiscott** [comment]
你的事务是控制在dao层吗
